### ISSUE TITLE
Why is the mod in 1.19.2 asking for 1.18 on the server? :V

### ISSUE THREAD

**Issue by Darkmega18** [mactso/HarderMonsterBoats#2]
[crash-2023-06-15_23.40.04-fml.txt](https://github.com/mactso/HarderMonsterBoats/files/11758201/crash-2023-06-15_23.40.04-fml.txt)
instant crash. only version of 1.19.2 you have when I go to start it up.

**Comment by mactso** [comment]
Not sure!  For some reason, I didn't see your message until today.  I'll look at this tonight.  Sorry about the delay.
It's likely that when I missed amod configuration file entry.  Not sure why it didn't fail in testing tho. 

Looking at it.

**Comment by mactso** [comment]
Wish I had seen this sooner.  I did have a reference to 1.18 in the configuration file.

Fixing this and uploading.

**Comment by mactso** [comment]
I've fixed this and tested in on the 1.19 servers.
I've submitted this for approval.

Thanks so much for the bug report!
It's been a rough couple weeks in real life.

Cheers,
Two Guys,
MacTso

**Comment by Darkmega18** [comment]
> I've fixed this and tested in on the 1.19 servers. I've submitted this for approval.
> 
> Thanks so much for the bug report! It's been a rough couple weeks in real life.
> 
> Cheers, Two Guys, MacTso

oh, I see. Thanks for the eventual fix. Cause I didn't want to blanket the boat anti-cheese with the better AI version. so good that you got this back together.

I hope it's going better for you, mactso. Less stressful and stuff.
